### ISSUE TITLE
ActiveRecord::StatementInvalid: Could not find table 'persons'

### ISSUE THREAD

**Issue by brianwang** [openbookie/sportbook#3]
hi, I follow README to install local environment, but when I run "rake db:setup" command,
I get the following errror:
ActiveRecord::StatementInvalid: Could not find table 'persons'

it is very clear that i missing persons table in sqllite database, please help. Do i missed something?

**Comment by geraldb** [comment]
Please post installation questions to the [forum / mailing list](http://groups.google.com/group/opensport). Thanks. Cheers.
