### ISSUE TITLE
cannot load such file -- logutils/db (LoadError)

### ISSUE THREAD

**Issue by pitabasprathal** [openbookie/sportbook#5]

**Comment by geraldb** [comment]
@pitabasprathal  Thanks for trying sportbook. Please send your installation / setup questions to the [mailinglist / forum](https://groups.google.com/group/opensport). Cheers.

**Comment by giangm9** [comment]
The link is died, how can i send the installation questions ?

**Comment by geraldb** [comment]
The link / forum still works and is good. Cheers.
